### PR TITLE
Improvements to Simple segmenter

### PR DESCRIPTION
**Pull request by michnov**
1. deal with multiple consecutive spaces in input sentences or the space at the start/end of the sentence
    => no sentence boundary
2. do not strip possible trailing space from the sentence. When applying tokenize.Simple afterwards with normalize_spaces=0, it correctly fills the whitespace-related MISC features => the text can be reconstructed in its original form
3. if an abbreviation of the first name is the first word of a quoted segment, delete the starting quotation mark to find out if the word consists of two chars, e.g. in "„A. Merkel ..."

### CODE REVIEW

**Comment by michnov** [comment]
The reason why I need (2) could be possibly fixed in a better way. I may think about it later.

**Comment by martinpopel** [comment]
I would suggest `if not self.normalize_spaces: segments[-1] += ' '` (and set `normalize_space=True` by default) and then I would happily merge this PR (if you re-open it).

**Comment by michnov** [comment]
Thanks, I closed it since I immediately discovered a related issue caused by using read.Sentences rstrip=''. The tree.text then contains \n or \r characters, which cause problems in write.Conllu. For the time being, I fixed it locally in write.Conllu by striping the trailing \n or \r. Now I see that it's not as related to the (2) issue as I thought at 3am :laughing: Anyway, I'll add it to this PR.

**Comment by martinpopel** [comment]
Thanks.

**Pull request merged**
