### PR TITLE
Update vislcg.py

### PR DESCRIPTION
**Pull request by ftyers**
This fixes the бир нәрсе problem, but leaves a problem with multiwords... e.g. 

2-3	екеуі де	_	_	_	_	_	_	_	_
2	екеуі	екеу	_	num	px3sp|nom	1	appos	_	_
3	де	"да	_	postadv	_	2	advmod	_	_

### CODE REVIEW

**Comment by martinpopel** [comment]
Please, can you report the VISLcg input on which the current `read.Vislcg` fails? You are reporting just the broken CoNLL-U output and it is difficult for me to reconstruct the input and add a test case. 

For example, this minimal test case
```
echo '"<Олар>"
	"олар" prn pers p3 pl nom @nsubj #1->0
"<екеуі де>"
	"екеу" num coll subst px3sp nom @appos #2->1
		"да" postadv @advmod #3->2
"<бір нәрсе>"
	"бір нәрсе" prn ind nom @obj #4->1
' | | udapy -s read.Vislcg
```
seems to work with the current `read.Vislcg` (checked in master, based on `shlex.split`).

**Comment by martinpopel** [comment]
BTW: I understand the motivation for masking empty copulas with multiword tokens (although this solution was not chosen as valid for UDv2), but I have no idea why "екеуі де" is annotated as a multiword token. It contains a space, so the word splitting is obvious.

**Comment by ftyers** [comment]
Yes, unfortunately we chose the way of dealing with the empty copula morpheme in p3 is based on our existing system, which we would like to maintain compatibility with. 

Regarding "екеуі де", again this is for compatibility purposes and for generation. For clitics where the form of the clitic depends on the previous word (e.g. -DA [-де, -да, -те, -да]), or there can be an intervening copula, then we keep it as a single token.

**Comment by ftyers** [comment]
Now I get:

```
$ udapy -s read.Vislcg < ~/source/apertium/languages/apertium-kaz/texts/story.tagged.txt 
2017-02-21 11:28:20,348 [   INFO] execute -  ---- ROUND ----
2017-02-21 11:28:20,349 [   INFO] execute - Executing block Vislcg
Traceback (most recent call last):
  File "/home/fran/local/bin/udapy", line 4, in <module>
    __import__('pkg_resources').run_script('udapi-python==0.1', 'udapy')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1512, in run_script
    exec(script_code, namespace, namespace)
  File "/home/fran/local/lib/python3.5/site-packages/udapi_python-0.1-py3.5.egg/EGG-INFO/scripts/udapy", line 70, in <module>
  File "/home/fran/local/lib/python3.5/site-packages/udapi_python-0.1-py3.5.egg/udapi/core/run.py", line 153, in execute
  File "/home/fran/local/lib/python3.5/site-packages/udapi_python-0.1-py3.5.egg/udapi/core/basereader.py", line 113, in process_document
  File "/home/fran/local/lib/python3.5/site-packages/udapi_python-0.1-py3.5.egg/udapi/core/basereader.py", line 75, in filtered_read_tree
  File "/home/fran/local/lib/python3.5/site-packages/udapi_python-0.1-py3.5.egg/udapi/block/read/vislcg.py", line 30, in read_tree
  File "/home/fran/local/lib/python3.5/site-packages/udapi_python-0.1-py3.5.egg/udapi/block/read/vislcg.py", line 66, in _node
  File "/usr/lib/python3.5/shlex.py", line 273, in split
    return list(lex)
  File "/usr/lib/python3.5/shlex.py", line 263, in __next__
    token = self.get_token()
  File "/usr/lib/python3.5/shlex.py", line 90, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.5/shlex.py", line 166, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation
```

Here is the input file:

https://svn.code.sf.net/p/apertium/svn/languages/apertium-kaz/texts/story.tagged.txt

I'm installing with:

```
   python3 setup.py clean
   python3 setup.py build 
   python3 setup.py install --prefix=/home/fran/local
```

**Comment by martinpopel** [comment]
> story.tagged.txt

The VISLcg is really a funny format if the following line is valid
```
""" sent @punct #2->9
```
Are you sure the quote should not be quoted somehow (e.g. `"\""`)?
Now I understand the motivation for this pull request and I will merge it once you confirm the question above.

> This fixes the бир нәрсе problem, but leaves a problem with multiwords.

Can you provide the input VISLcg which shows the mulitword problem?

**Comment by ftyers** [comment]
Yes, it's not escaped, just """. And yes, it is quite a funny format :)

In this sentence, when I made the change I got an extraneous " before the lemma of 'да'.

```
"<Олар>"
	"олар" prn pers p3 pl nom @nsubj #1->7
"<екеуі де>"
	"екеу" num coll subst px3sp nom @appos #2->1
		"да" postadv @advmod #3->2
"<көңілді>"
	"көңілді" adj advl @advmod #4->7
"<үйге>"
	"үй" n dat @obl #5->7
"<қарай>"
	"қарай" post @case #6->5
"<келе>"
	"кел" v iv prc_impf @parataxis #7->16
"<жатыр>"
	"жат" vaux pres p3 sg @aux #8->7
"<,>"
	"," cm @punct #9->16
"<бір нәрсе>"
	"бір нәрсе" prn ind nom @obj #10->11
"<жеп>"
	"же" v tv gna_perf @advcl #11->14
"<,>"
	"," cm @punct #12->11
"<су>"
	"су" n nom @obj #13->14
"<ішетін>"
	"іш" v tv gpr_impf @acl #14->15
"<уақыт>"
	"уақыт" n nom @nsubj #15->16
"<болды>"
	"бол" v iv ifi p3 sg @root #16->0
"<!>"
	"!" sent @punct #17->16
```

**Comment by martinpopel** [comment]
I hope 0146cf4 fixes the bug.

**Pull request merged**
